config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
  get '/menu', to: 'pages#menu'

  namespace :system do
    resources :users
    resources :houses
    resources :scores
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/house.rb
# frozen_string_literal: true

class House < ApplicationRecord
  has_many :users
  has_many :scores

  validates :name, presence: true

  before_destroy :clear_users_collection

  private

  def clear_users_collection
    users.clear
  end
end

app/models/score.rb
# frozen_string_literal: true

class Score < ApplicationRecord
  belongs_to :house

  validates :value, inclusion: 1..12
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  belongs_to :house, optional: true

  enum role: {
    admin: 0,
    coach: 1
  }

  validates :email_address, :password, :role, presence: true
  validates :house, presence: true, on: %i[create update]
  validates :role, inclusion: { in: roles.keys }
  validates :email_address, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# Controls all general pages
class PagesController < ApplicationController
  def menu; end
end

app/controllers/system/houses_controller.rb
# frozen_string_literal: true

module System
  # Controls the houses
  class HousesController < ApplicationController
    def index
      @houses = House.all
    end

    def new
      @house = House.new
    end

    def create
      @house = House.new(house_params)
      if @house.save
        flash[:success] = 'House successfully created'
        redirect_to system_houses_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @house = House.find(params[:id])
    end

    def update
      @house = House.find(params[:id])
      if @house.update(house_params)
        flash[:success] = 'House was successfully updated'
        redirect_to system_houses_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @house = House.find(params[:id])
      if @house.destroy
        flash[:success] = 'House was successfully deleted.'
      else
        flash[:error] = 'Something went wrong'
      end
      redirect_to system_houses_url
    end

    private

    def house_params
      params.require(:house)
            .permit(:name)
    end
  end
end

app/controllers/system/scores_controller.rb
# frozen_string_literal: true

module System
  # Controls the scores of the scores (admin-only)
  class ScoresController < ApplicationController
    def index
      @scores = Score.all
    end

    def new
      @score = Score.new
    end

    def create
      @score = Score.new(score_params)
      if @score.save
        flash[:success] = 'Score successfully created.'
        redirect_to system_scores_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @score = Score.find(params[:id])
    end

    def update
      @score = Score.find(params[:id])
      if @score.update(score_params)
        flash[:success] = 'Score was successfully updated.'
        redirect_to system_scores_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @score = Score.find(params[:id])
      if @score.destroy
        flash[:success] = 'Score was successfully deleted.'
      else
        flash[:error] = 'Something went wrong'
      end
      redirect_to system_scores_url
    end

    private

    def score_params
      params.require(:score)
            .permit(:house_id, :value)
    end
  end
end

app/controllers/system/users_controller.rb
# frozen_string_literal: true

module System
  # Controls the users
  class UsersController < ApplicationController
    def index
      @users = User.all
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        flash[:success] = 'User successfully created'
        redirect_to system_users_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:success] = 'User was successfully updated'
        redirect_to system_users_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @user = User.find(params[:id])
      if @user.destroy
        flash[:success] = 'User was successfully deleted.'
      else
        flash[:error] = 'Something went wrong'
      end
      redirect_to system_users_url
    end

    private

    def user_params
      params.require(:user)
            .permit(:email_address, :password, :house_id, :role)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/system/houses_helper.rb
# frozen_string_literal: true

module System
  # Helper for houses
  module HousesHelper
    def house_select_options
      House.pluck(:name, :id)
    end
  end
end

app/helpers/system/scores_helper.rb
module System::ScoresHelper
end

app/helpers/system/users_helper.rb
module System::UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Concentrate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <aside class="container mx-auto my-8 px-5">
      <h1 class="text-xl font-bold">Battle of the Houses</h1>
      <p><%= link_to 'Menu', menu_path %></p>
    </aside>

    <div class="container mx-auto my-8 px-5">
      <% flash.each do |name, message| %>
        <% if name == 'success' %>
          <div class="flash-message flash-message__success">
            <%= message %>
          </div>
        <% else %>
          <div class="flash-message flash-message__error">
            <%= message %>
          </div>
        <% end %>
      <% end %>
    </div>

    <main class="container mx-auto px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<div class="flex justify-center">
  <div class="bg-gray-300 rounded-md p-5">
    <%= form_with url: "/", method: :get do |form| %>
      <div class="mb-5">
        <%= form.label :class_time, 'Werktijd:' %>
        <%= form.number_field :class_time, value: 20, in: 5..45 %>
        min.
      </div>

      <div class="mb-5">
        <%= form.label :free_time, 'Pauze:' %>
        <%= form.number_field :free_time, value: 5, in: 5..45 %>
        min.
      </div>

      <div class="mb-5">
        <div>
          <%= form.radio_button :class_type, 'house_time', checked: true %>
          <%= form.label :class_type_screen, 'Huistijd' %>
        </div>
        <div>
          <%= form.radio_button :class_type, 'class_time' %>
          <%= form.label :class_type_remote, 'Les' %>
        </div>
      </div>
      <div class="mb-5">
        <div>
          <%= form.radio_button :device, 'screen' %>
          <%= form.label :device_screen, 'Scherm' %>
        </div>
        <div>
          <%= form.radio_button :device, 'remote', checked: true %>
          <%= form.label :device_remote, 'Afstandsbediening' %>
        </div>
      </div>

      <%= form.submit "Start", class: 'bg-emerald-500' %>
    <% end %>
  </div>
</div>

<div class="flex justify-center p-5">
  <p>Verbonden met "Scherm 1"</p>
</div>

app/views/pages/menu.html.erb
<nav>
  <h2 class="text-lg">General</h2>
  <ol class="pl-4 mb-4">
    <li><%= link_to 'Home', root_path %></li>
  </ol>

  <h2 class="text-lg">System</h2>
  <ol class="pl-4 mb-4">
    <li><%= link_to 'Users', system_users_path %></li>
    <li><%= link_to 'Houses', system_houses_path %></li>
    <li><%= link_to 'Scores', system_scores_path %></li>
  </ol>
</nav>

app/views/partials/system/_form_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="p-4 my-8 border border-red-500 bg-red-200">
    <h2><%= pluralize(object.errors.count, 'error') %> prohibited this object from being saved:</h2>
    <ul class="list-disc">
      <% object.errors.each do |error| %>
        <li class="ml-5"><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/system/houses/_form.html.erb
<%= render partial: 'partials/system/form_errors', locals: { object: @house } %>

<%= form_with model: [:system, @house] do |form| %>
  <%= form.label :name %><br>
  <%= form.text_field :name %><br>

  <%= form.submit %>
<% end %>

app/views/system/houses/edit.html.erb
<h2 class="text-lg">System - Edit house</h2>
<%= render partial: 'form' %>

app/views/system/houses/index.html.erb
<h2 class="text-lg">System - Houses</h2>
<%= link_to "New house", new_system_house_path %>

<% if @houses.any? %>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Created at</th>
        <th>Updated at</th>
      </tr>
    </thead>
    <tbody>
      <% @houses.each do |house| %>
        <tr>
          <td><%= house.id %></td>
          <td><%= house.name %></td>
          <td><%= house.created_at %></td>
          <td><%= house.updated_at %></td>
          <td>
            <%= link_to 'Edit', edit_system_house_path(house) %>
          </td>
          <td>
            <%= button_to 'Delete', [:system, house], method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/system/houses/new.html.erb
<h2 class="text-lg">System - New house</h2>
<%= render partial: 'form' %>

app/views/system/scores/_form.html.erb
<%= render partial: 'partials/system/form_errors', locals: { object: @score } %>

<%= form_with model: [:system, @score] do |form| %>

  <%= form.label :house_id %><br>
  <%= form.select :house_id, house_select_options, { prompt: 'Select' } %><br>

  <%= form.label :value %><br>
  <%= form.number_field :value, in: 0..12 %><br>

  <%= form.submit %>
<% end %>

app/views/system/scores/edit.html.erb
<h2 class="text-lg">System - Edit score</h2>
<%= render partial: 'form' %>

app/views/system/scores/index.html.erb
<h2 class="text-lg">System - Scores</h2>
<%= link_to "New score", new_system_score_path %>

<% if @scores.any? %>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>House ID</th>
        <th>Value</th>
        <th>Created at</th>
        <th>Updated at</th>
      </tr>
    </thead>
    <tbody>
      <% @scores.each do |score| %>
        <tr>
          <td><%= score.id %></td>
          <td>
            <% if score.house %>
              <%= "#{score.house.name} (#{score.house_id})" %>
            <% else %>
              -
            <% end %>
          </td>
          <td><%= score.value %></td>
          <td><%= score.created_at %></td>
          <td><%= score.updated_at %></td>
          <td>
            <%= link_to 'Edit', edit_system_score_path(score) %>
          </td>
          <td>
            <%= button_to 'Delete', [:system, score], method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/system/scores/new.html.erb
<h2 class="text-lg">System - New score</h2>
<%= render partial: 'form' %>

app/views/system/users/_form.html.erb
<%= render partial: 'partials/system/form_errors', locals: { object: @user } %>

<%= form_with model: [:system, @user] do |form| %>
  <%= form.label :email_address %><br>
  <%= form.email_field :email_address %><br>

  <%= form.label :password %><br>
  <%= form.password_field :password %><br>

  <%= form.label :house_id %><br>
  <%= form.select :house_id, house_select_options, { prompt: 'Select' } %><br>

  <%= form.collection_radio_buttons :role, User.roles, :first, :first do |collection| %>
    <%= collection.radio_button %>
    <%= collection.label class: 'capitalize' %><br>
  <% end %>

  <%= form.submit %>
<% end %>

app/views/system/users/edit.html.erb
<h2 class="text-lg">System - Edit user</h2>
<%= render partial: 'form' %>

app/views/system/users/index.html.erb
<h2 class="text-lg">System - Users</h2>
<%= link_to "New user", new_system_user_path %>

<% if @users.any? %>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Email address</th>
        <th>Password</th>
        <th>House ID</th>
        <th>Role</th>
        <th>Created at</th>
        <th>Updated at</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.email_address %></td>
          <td><%= user.password %></td>
          <td>
            <% if user.house %>
              <%= "#{user.house.name} (#{user.house_id})" %>
            <% else %>
              -
            <% end %>
          </td>
          <td><%= user.role %></td>
          <td><%= user.created_at %></td>
          <td><%= user.updated_at %></td>
          <td>
            <%= link_to 'Edit', edit_system_user_path(user) %>
          </td>
          <td>
            <%= button_to 'Delete', [:system, user], method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/system/users/new.html.erb
<h2 class="text-lg">System - New user</h2>
<%= render partial: 'form' %>